### ISSUE TITLE
Eggman objects visible after enabling debug mode while in normal state

### ISSUE THREAD

**Issue by BooBerry** [ElspethThePict/S2Absolute#9]
Greetings! I'm not sure if you're taking issue reports or if this is a known issue or not, but I thought I'd report it just in case. I do apologize in advance if you're not taking reports and/or if it's already known.

I downloaded the latest build (with the commits from 19~ hours ago) and noticed when you enable debug mode (by enabling the level select from title screen then using the sound test debug mode code) that Eggman blocks/objects now appear in levels, especially around hazards (e.g. crushing hazards) that can kill you.

I'm aware Eggman blocks/objects appearing after enabling debug mode is normal, but as far as I know they should only appear when you engage debug mode, not while in a "normal" state.

Screenshot example of normal Sonic with an Eggman block/object visible:

![Screenshot 2024-08-03 090202](https://github.com/user-attachments/assets/708d6dfc-a830-45a1-b65b-8c2fd37f4b13)

I used MCZ as an example here, but it'll appear in all levels. Of course I also checked S1F and it's fine there, Eggman blocks/objects only appear when engaging debug mode. Also checked S2A 1.2.1 and it functions like this there too. Not using any other mods, downloaded from GH as-is.

Regards!

**Comment by ElspethThePict** [comment]
Hi BooBerry.

Thanks for raising an issue. This is definitely the best way to report bugs and such in the projects.

However this is a deliberate change to make development easier. Debug mode has been changed in a few ways to make our dev work easier, and the invisible objects always being visible is one of them. Try pressing the X button (Q on keyboard on L1 on controller) to see another 😉

**Comment by BooBerry** [comment]
Great, thanks for confirming (and thanks for the X button tip, will come in handy!).

One question though, this behavior can be disabled/reversed via a mod, correct? My thinking is when the new S1F/S2A versions are released with this change that there are some users who play with debug mode enabled (for whatever reason) and this may be something somebody (who doesn't know any different regarding this change) will report again.

**Comment by ElspethThePict** [comment]
Yeah, anything can be changed with a mod.
